### ISSUE TITLE
Add new snippets, Fix existing snippets - Hacktoberfest

### ISSUE THREAD

**Issue by monizb** [monizb/vscode-regex-snippets#1]
This should be one of the easiest way to get a lot of PRs merged!
You can fix an existing snippet or submit a new snippet which you think will help other developers.
Feel free to start a conversation below to ask any doubts.

**Comment by apoorva1999** [comment]
Hello, I'm interested in contributing to this issue

**Comment by monizb** [comment]
@apoorva1999 Sure!

**Comment by apoorva1999** [comment]
Thank you, can you guide me about how to submit a new snippet, is there any documentation for the same?

**Comment by monizb** [comment]
Yes sure, if you look in [this](https://github.com/monizb/vscode-regex-snippets/blob/master/regexsnippets.code-snippets) file, you will see that each node in the JSON tree has 3 properties:
1) Prefix: this is the shortcode which the users have to type in so that this extension pops up and gives them the entire snippet, this should always start with `!`
2) Body: this is the place where you put in the actual snippet, Now if you want input from a user in any part of the code you will add this: ```${1 : nameofinput}``` so automatically when the snippet is pasted in, the cursor will be replaced to start from this part of the code.
3) Description: This is where you enter a short description about what your snippet actually does

Hope this helps you out, please let me know if you face any difficulties :)

**Comment by apoorva1999** [comment]
That helps, thank you :)
