### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by monizb** [monizb/vscode-regex-snippets#2]
Add a basic CONTRIBUTING.md file with basic template to the repository.

**Comment by Poobalan1210** [comment]
I would like to work on this issue

**Comment by monizb** [comment]
@Poobalan1210  Please go ahead

**Comment by Poobalan1210** [comment]
can I start working on October 1

**Comment by Poobalan1210** [comment]
for hacktoberfest

**Comment by monizb** [comment]
@Poobalan1210  yes sure, this issue is specifically for Hacktoberfest :)
