### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by akhilesh-balaji** [monizb/vscode-regex-snippets#7]
I just got this extension, and I was going to use it for **Python**, but have no idea how to use it: are the snippets supposed to be inside the string or outside?

This is my code:
```
import re
while True:
    email = input("Email Adress: ")
    m = re.match(r"([a-zA-z0-9.]+)@([a-z0-9]+\.[a-z]+)", email)
    if m is None:
        print("Invalid E-mail. Please try again.") 
    else:
        print("Username: ", m.group(1))
        print("Domain Name: ", m.group(2))
```

I want to use the `!valemail` snipped from this extension instead of `r"([a-zA-z0-9.]+)@([a-z0-9]+\.[a-z]+)"`.

**Comment by jonathantwite** [comment]
Apparently this extension only registers the snippets for JavaScript, TypeScript, React and Angular files: https://github.com/monizb/vscode-regex-snippets/blob/56af491a755717a4cc7419fae693c237a0476851/package.json#L19-L36

As to the email regex, that is currently not a very good implementation and needs changing

**Comment by akhilesh-balaji** [comment]
Oh ok. That's too bad then 😐

**Comment by monizb** [comment]
The extension now has version **[1.0.2]** with added support for Python!
