### ISSUE TITLE
Incorrect Email Validation Regex

### ISSUE THREAD

**Issue by jonathantwite** [monizb/vscode-regex-snippets#8]
**Describe the bug**
Email validation is notoriously hard as the rules are complex and cannot be directly translated into a regex.  However the email validation regex snippet in this does project is broken as to not obey some of the basic rules.

* The local part should allow all of the following characters: 
```
!#$%&'*+-/=?^_`{|}~
```
* The local part should not be able to start or end with a `.` (full-stop).

* Currently the domain part allows any number of non-linebreaking characters (including all special characters of any type): `.+.`.  Domains should not have special characters.
* Assuming that `.+.` should be `\.+`, the limiting of the top-level domain to 2-4 characters long prevents many (most) of the newer top-level domains.

**To Reproduce**
1. Use a Regex validator, paste in the regex generated by this extension
1. The following should be acceptable but are currently not:
    * `jack$1@mycompany.com`
    * `o'reilly@mycompany.com`
    * `jack@mycompany.design` (this currently matches due to the `.` matching issue).
1. The following should not be acceptable but currently are:
    * `john@smith@mycompany.com`
    * `jack@my^company.com`
    * `john.@mycompany.com`
    * `.smith@mycompany.com`

**Expected behavior**
As explained above

**Additional context**
Even with these changes this will not be a comprehensive email validator but catches the basics which matches most implementations.

**Comment by monizb** [comment]
Hey @jonathantwite sorry for the late reply, If I am not wrong the regex code provided by you is not passing any of the tests, and yes, you were right about it failing for all the test cases mentioned by you.
I have come up with another regex code like: `/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g`

Right now the above expressions fails for: john.@mycompany.com and .smith@mycompany.com. Do let me know what you think

**Comment by monizb** [comment]
@jonathantwite any updates? 😁 thanks!
